### ISSUE TITLE
Errors with Tensor Flow 0.9

### ISSUE THREAD

**Issue by fobus42** [ilblackdragon/tf_examples#4]
Hello, I'm unable to run this example with tensor flow 9.

Here is my bug reports on tensorflow issue tracker : 

https://github.com/tensorflow/tensorflow/issues/3167
https://github.com/tensorflow/tensorflow/issues/3169

**Comment by fobus42** [comment]
Any update for this?

**Comment by fobus42** [comment]
I'm not writing for the fix. I'm wondering for you! Are you alive?

**Comment by ilblackdragon** [comment]
haha, I was out for vacation and work traveling =) Let me take a look - we just removed all the old `TensorFlowXXX` classes from `tf.learn` - so should rewamp all the examples.

**Comment by ilblackdragon** [comment]
Just updated everything in titanic.py - can you please check if it all works? (note was updating for latest version of TF 0.10)

**Comment by fobus42** [comment]
Hi, Thank you for your response. It is nice to know you are alive :) I'm going to check and write here if anything is not working.

Thanks.
